fix: Properly document the new config style for Cassandra
gatling/frontline-doc pull request #41
Opened 2022-03-07 16:04 UTC by guilgaly

ref: MISC-334
ref: MISC-339

Motivation:

The config sample isn't correct for the new Cassandra config style. We also don't warn against mixing and matching with deprecated keys.

Modifications:

- Fix the sample config file
- Add a warning about the deprecated Cassandra config style

2022-03-07 16:11 UTC, guilgaly commented
Notes:
- we can add the same comments to `frontline-defaults.conf` in the app so they appear in the generated file
- `frontline-advanced-defaults.conf` in the app includes a key `datastax-java-driver.basic.request.timeout`... I don't see how that could work in the self-hosted/v1 code base, where we load the Cassandra config specifically from `frontline.cassandra`?

I'll check that last one and probably do a PR on `frontline`.

2022-03-07 17:13 UTC, Isammoc requested changes

2022-03-07 17:13 UTC, Isammoc commented on content/reference/current/installation/configuration/includes/frontline.conf
> +  }
????
Should be at top level, shouldn't be?
(here it is inside `frontline`)

Or what do I miss to understand the PR?

2022-03-07 17:27 UTC, guilgaly commented
See also: gatling/frontline#1517

2022-03-07 19:26 UTC, Isammoc commented on content/reference/current/installation/configuration/includes/frontline.conf
> +  }
Oh! Indeed! It was intended to be used for defining environment variable.

2022-03-07 19:43 UTC, Isammoc approved these changes

2022-03-07 19:43 UTC, Isammoc commented on content/reference/current/release/release-notes/index.md
> +* FL-589: Cassandra: Expose full Cassandra Java Driver configuration with Typesafe config (eg configuring TLS)
:+1:

2022-03-10 14:34 UTC, tpetillot approved these changes

2022-03-15 08:14 UTC, merged