doc: advice user to shutdown cassandra before saving data folder, closes MISC-392
gatling/frontline-doc pull request #50
Opened 2022-06-21 09:15 UTC by tpetillot

**Motivation:**
Prevent corrupted data.

2022-06-21 09:16 UTC, Isammoc approved these changes

2022-06-21 09:16 UTC, slandelle requested changes

2022-06-21 09:16 UTC, slandelle commented on content/reference/current/installation/manual/index.md
> +  _(eg `/var/lib/cassandra` directory, but might vary depending on how you've installed Cassandra)_
Explain how to shutdown Cassandra.
If installed as a service, stop the service.
Otherwise, just kill the process.

2022-06-23 07:42 UTC, closed without merging

2022-06-23 07:42 UTC, tpetillot commented
Closed in favor of https://gatlingcorp.atlassian.net/browse/MISC-336