Update documentation for 1.17.0
gatling/frontline-doc pull request #52
Opened 2022-07-11 09:21 UTC by ccedric

Modifications:
- We now support cassandra 4
- Updated Print Pdf section
- Updated Gce page
- small typos fixed

2022-07-11 09:43 UTC, slandelle requested changes

2022-07-11 09:43 UTC, slandelle commented on content/reference/current/installation/docker/index.md
> +We will be using the official Cassandra image under the tag name `cassandra:4`.
If we do that, we must also:
* update the installer to use Cassandra 4
* document the migration path

2022-07-13 11:53 UTC, Isammoc approved these changes

2022-07-13 13:32 UTC, notdryft commented on content/reference/current/installation/manual/index.md
> +`num_tokens: 16`
```suggestion
```yaml
num_tokens: 16
```
```

2022-07-13 13:34 UTC, notdryft commented on content/reference/current/installation/manual/index.md
> +- Cassandra 3 supports only JDK 8, while Cassandra 4 support JDK 8 &  11.
```suggestion
- Cassandra 3 supports only JDK 8, while Cassandra 4 supports JDK 8 & 11.
```

2022-07-13 13:34 UTC, notdryft commented on content/reference/current/user/reports/index.md
> +## Print PDF
```suggestion
## Print to PDF
```

2022-07-13 15:07 UTC, merged